### ISSUE TITLE
Add a DataSource for the task database

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-kubernetes#28] opened 2016-01-21 23:58 UTC
The spring-cloud-dataflow-admin-starter now creates the task database tables on start-up. All SPI implementations should add a DataSource to their configuration to be used for the tasks.

**Comment by sabbyanandan** [comment] 2016-05-23 15:13
Duplicate of spring-cloud/spring-cloud-dataflow-server-kubernetes#73

**Closed by sabbyanandan** 2016-05-23 15:13 UTC
