### ISSUE TITLE
Restarting a failed batch job gives an error as it adds 2 driver classes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#351] opened 2018-10-29 16:32 UTC
_From @siddhantsorann on October 26, 2018 10:10_

Description:
When I restart a failed batch job it gives me an error as I think it's re-adding the driver class. 

Release versions:
1.7.0.RELEASE Kubernetes Server

Steps to reproduce:
1. Run a failing batch job
2. Restart it from UI 

Error:

`Cannot load driver class: org.mariadb.jdbc.Driver,org.mariadb.jdbc.Driver`

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.dataSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver,org.mariadb.jdbc.Driver
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]

```

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2519_

**Comment by sabbyanandan** [comment] 2018-10-29 16:32
When reporting problems like this, you'd have to share more details. Did the job run successfully in the first run? What is the full stacktrace? Better yet, can you share the batch-job?

**Comment by sabbyanandan** [comment] 2018-10-29 16:32
_From @siddhantsorann on October 29, 2018 5:59_

I purposely failed the job on the first run to test the restart job feature. When I restarted the failed job it didn't start the task only because I got the above error. Basically, the driver is not recognized as its been added twice. It's pretty much like this issue... https://github.com/spring-cloud/spring-cloud-dataflow/issues/1800

**Comment by chrisjs** [comment] 2018-10-30 15:55
@siddhantsorann not able to reproduce what your seeing. i see artificial exceptions i inserted and `JobInstanceAlreadyCompleteException`'s but i don't see any driver exceptions that you mentioned.

can you provide the exact steps and even better if possible, sample code to go along with it so i can reproduce?

**Comment by siddhantsorann** [comment] 2018-10-31 06:47
Sure. Give me some time.

**Comment by chrisjs** [comment] 2018-11-01 15:55
closing for now, please re-open when reproducible.

**Closed by chrisjs** 2018-11-01 15:55 UTC
Labels: in progress, waiting-for-feedback

**Comment by chrisjs** [comment] 2018-11-26 13:31
@siddhantsorann can you provide a reproducible sample that I can run?

**Comment by siddhantsorann** [comment] 2018-11-26 13:34
@chrisjs You can try with a sample batch application. Even that is adding 2 drivers on restart. I have given the driver, url etc details in the rabbitmq-config and I am connecting to a DB on redshift not running one on kubernetes.

**Comment by siddhantsorann** [comment] 2018-11-27 05:52
@chrisjs I ran the sample batch job "spring-cloud-dataflow/spring-cloud-task/spring-cloud-task-samples/batch-job" but with spring boot 1.5.17 RELEASE and got the same error. Please try it with changing the spring boot parent to 1.5.17 and you should get the error too.

**Comment by chrisjs** [comment] 2018-11-27 14:31
@siddhantsorann what version of `spring-cloud-task` are you using? also, if the issue is reproducible by just running the sample outside of kubernetes, the `spring-cloud-task` project / gitter channel would be more appropriate to raise this issue.

**Comment by siddhantsorann** [comment] 2018-12-03 07:50
@chrisjs I am using the spring-cloud-starter-task 2.0.0.RELEASE. And no, it's not reproducible outside of kubernetes.
