### ISSUE TITLE
Add kubernetes server docker image to docker hub

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#48] opened 2016-02-29 15:42 UTC
Depends on #18.

**Comment by ericbottard** [comment] 2016-03-02 16:24
Seems like a dupe of #18

**Comment by trisberg** [comment] 2016-05-31 16:20
https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes/

**Closed by trisberg** 2016-05-31 16:20 UTC
Labels: in progress
